Origin/feature/plugin gcs done file marker
AdaptiveScale/google-cloud pull request #26
Opened 2020-11-27 10:13 UTC by dardanxh

2020-11-27 13:03 UTC, ardian4 requested changes
1. After making the necessary changes, we usually practice squashing all the commits into one.
2. Are you getting two test failures related with BigTable after running `mvn clean package`?
3. You can check style with this command `mvn clean package -DskipTests`

2020-11-27 13:03 UTC, ardian4 commented on src/main/java/io/cdap/plugin/gcp/gcs/actions/GCSDoneFileMarker.java
> +package io.cdap.plugin.gcp.gcs.actions;
Missing Copyright

2020-11-27 13:03 UTC, ardian4 commented on src/main/java/io/cdap/plugin/gcp/gcs/actions/GCSDoneFileMarker.java
> +                    (new ConditionConfig(this.runCondition)).validate();
We can use `io.cdap.plugin.common.batch.action.ConditionConfig#validate(io.cdap.cdap.etl.api.FailureCollector)`and remove try/catch block

2020-11-27 13:03 UTC, ardian4 commented on pom.xml
Usually we don't  have to make any changes in pom.xml except when we have to upgrade dependencies, for testing in development plugins you can download CDAP Sandbox 6.3 here : https://builds.cask.co/artifact/CDAP-BUT/shared/build-2594/SDK/cdap/cdap-standalone/target

2020-11-27 13:03 UTC, ardian4 commented on src/main/java/io/cdap/plugin/gcp/gcs/actions/GCSDoneFileMarker.java
> +package io.cdap.plugin.gcp.gcs.actions;
Are you using code standard from this source: https://wiki.cask.co/display/CE/Coding+Standard because I am getting different result when I am re-formatting the code?

2020-11-27 13:39 UTC, nbesimi commented on pom.xml
> +    <cdap.version>6.2.3</cdap.version>
@ardian4 do you have any comment about changing this from 6.3.0-SNAPSHOT to 6.2.3?
Does the PR needs to have POM changes?

2020-11-27 13:39 UTC, nbesimi commented on pom.xml
> +            <parent>system:cdap-data-pipeline[6.2.0-SNAPSHOT,7.0.0-SNAPSHOT)</parent>
@ardian4 
Same as above? Is this change required in the PR, or we should do this change just while testing our plugin in CDAP 6.2 and/or CDAP 6.1 for instance?

2020-11-27 13:39 UTC, nbesimi commented on pom.xml
> +            <parent>system:cdap-data-streams[6.2.0-SNAPSHOT,7.0.0-SNAPSHOT)</parent>
Same as the previous comment

2020-11-28 09:32 UTC, dardanxh commented on src/main/java/io/cdap/plugin/gcp/gcs/actions/GCSDoneFileMarker.java
> +package io.cdap.plugin.gcp.gcs.actions;
> 1. After making the necessary changes, we usually practice squashing all the commits into one.
> 2. Are you getting two test failures related with BigTable after running `mvn clean package`?
> 3. You can check style with this command `mvn clean package -DskipTests`

1. Will do this in the next PRs.
2. Yes, I've hit these two errors related with BigTable.
3. Will do this.

2021-02-07 20:14 UTC, closed without merging